-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 17:34:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contacts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contacts` (
  `contacts_id` INT NOT NULL,
  `full_name` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `message` VARCHAR(200) NULL,
  PRIMARY KEY (`contacts_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `customer_id` INT NOT NULL,
  `full_name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Orders_orders_id` INT NOT NULL,
  `Contacts_contacts_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `orders_id_idx` (`Orders_orders_id` ASC) VISIBLE,
  INDEX `contacts_id_idx` (`Contacts_contacts_id` ASC) VISIBLE,
  CONSTRAINT `orders_id`
    FOREIGN KEY (`Orders_orders_id`)
    REFERENCES `mydb`.`Orders` (`orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contacts_id`
    FOREIGN KEY (`Contacts_contacts_id`)
    REFERENCES `mydb`.`Contacts` (`contacts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `orders_id` INT NOT NULL,
  `date_order` TIMESTAMP NOT NULL,
  `Products_products_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `products_id_idx` (`Products_products_id` ASC) VISIBLE,
  CONSTRAINT `products_id`
    FOREIGN KEY (`Products_products_id`)
    REFERENCES `mydb`.`Products` (`products_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Price` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Price` (
  `price_id` INT NOT NULL,
  `price` DECIMAL(2,2) NULL,
  `Products_products_id` INT NOT NULL,
  `currency` CHAR(3) NULL,
  `discount` DECIMAL(5,4) NULL,
  PRIMARY KEY (`price_id`),
  INDEX `products_id_idx` (`Products_products_id` ASC) VISIBLE,
  CONSTRAINT `products_id`
    FOREIGN KEY (`Products_products_id`)
    REFERENCES `mydb`.`Products` (`products_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `products_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NULL,
  `product_desc` VARCHAR(150) NULL,
  `img` VARCHAR(150) NULL,
  `type` VARCHAR(45) NULL,
  `alt` VARCHAR(45) NULL,
  PRIMARY KEY (`products_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
